# syntax=docker/dockerfile:1
FROM nvcr.io/nvidia/pytorch:22.02-py3
WORKDIR /home
ENV DEBIAN_FRONTEND=noninteractive

# Install Dependencies
RUN apt-get update && apt-get install -y apt-utils git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 ffmpeg vim\
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Update pip and install some python dependencies
RUN pip3 install --upgrade pip setuptools
RUN pip3 install opencv-python jupyter pkgconfig

# Install decord from  and mmcv-full v1.4.0 (latest 1.4.6 does not play nice with VST repo)
RUN pip3 install decord mmcv-full==1.4.0 PyTurboJPEG

# Install Denseflow - optional package not yet working!
#RUN git clone https://github.com/open-mmlab/denseflow.git \
#    && cd denseflow && mkdir build && cd build \
#    && cmake -DCMAKE_INSTALL_PREFIX=$HOME/app -DUSE_HDF5=no -DUSE_NVFLOW=no .. \
#    && make -j \
#    && make install

# Install mmaction2
RUN apt-get update && apt-get install -y pkg-config
RUN git clone https://github.com/open-mmlab/mmaction2.git \
    && cd mmaction2 \
    && pip3 install -r requirements/build.txt \
    && pip3 install -r requirements/optional.txt \
    && pip3 install -v -e . \
    && mkdir data

# Install some python packages
RUN pip3 install jupyterlab -U && pip3 install wandb pytorch-lightning onnx webcolors

# Clone the Video-Swin-Transformer repo
RUN git clone https://github.com/SwinTransformer/Video-Swin-Transformer.git

#Copy test notebook
COPY AT_DEMO.ipynb /home/Video-Swin-Transformer/


CMD ["bash"]
